services:
  postgres_db:
    image: postgres:15-alpine
    container_name: slot_postgres_db
    environment:
      POSTGRES_DB: slot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  eureka-server:
    image: tykhegaming/slot-eureka-server:latest
    container_name: slot-eureka-server
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_THREADS_VIRTUAL_ENABLED=true
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Xlog:gc:stdout:time,uptime,level,tags

  slot-api-server:
    image: tykhegaming/slot-api-server:latest
    container_name: slot-api-server
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_THREADS_VIRTUAL_ENABLED=true
      - JWT_SECRET:your-super-secret-key-that-is-at-least-32-bytes-long
      - EUREKA_HOST:http://localhost:8761/eureka/
      - SERVER_PORT:8080
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Xlog:gc:stdout:time,uptime,level,tags

  slot-auth-service-9091:
    image: tykhegaming/slot-auth-service:latest
    container_name: slot-auth-service
    ports:
      - "9091:9091"
    deploy:
        resources:
            limits:
              cpus: '1.0'
              memory: 1024M
            reservations:
              cpus: '1.0'
              memory: 1024M
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_THREADS_VIRTUAL_ENABLED=true
      - POSTGRES_URL=jdbc:postgresql://postgres_db:5432/slot_db
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - JWT_SECRET:your-super-secret-key-that-is-at-least-32-bytes-long
      - JWT_PLAYER_SEESION_EXPIRATION:3600000
      - JWT_EMPLOYEE_SEESION_EXPIRATION:3600000
      - JWT_REFRESH_EXPIRATION:7200000
      - EUREKA_HOST:http://localhost:8761/eureka/
      - SERVER_PORT:9091
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Xlog:gc:stdout:time,uptime,level,tags