spring:
  application:
    name: SLOT-AUTH-SERVICE
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:9091}

seed:
  players:
    enabled: ${SEED_PLAYERS_ENABLED:true}
    source: ${SEED_SOURCE_PLAYERS:classpath:seed/players.v1.json}
  employees:
    enabled: ${SEED_EMPLOYEES_ENABLED:true}
    source: ${SEED_SOURCE_EMPLOYEES:classpath:seed/employees.v1.json}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}