spring.datasource.url=jdbc:h2:file:./data/auth-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


#logging.level.org.springframework.security=DEBUG

jwt.secret=your-super-secret-key-that-is-at-least-32-bytes-long
jwt.player-session-expiration=${JWT_PLAYER_SEESION_EXPIRATION:3600000}
jwt.employee-session-expiration=${JWT_EMPLOYEE_SESSION_EXPIRATION:3600000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:7200000}
jwt.issuer=slot-auth-service